import {blankState,stageMode,createCharacter,editCharacter,addReference,restoreState,resolveStudioState,compilePrompt,compileGeneration,createTake,promoteTake,MockCompiler} from './studio-core.js';
import {STYLE_PACK_LIST} from './style-packs.js';
import {forgeOrbital,sceneGlyph,editorialNote} from './ui-assets.js';
import {createLibraryRegistry,searchLibrary,validateLibraryRegistry,coverageFor,coverageDiagnostics,prepareEnrichmentOperation,ENRICHMENT_OPERATIONS,LIBRARY_SCHEMA_VERSION} from './library-data.js';

const KEY='promptforge-studio-v2';
const UI_KEY='promptforge-studio-ui-v1';
const $=id=>document.getElementById(id);
const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const motionOK=()=>!matchMedia('(prefers-reduced-motion: reduce)').matches;
const MAYA_PORTRAIT='assets/maya-cafe-portrait.png';
function demoState(){
  let next=createCharacter(blankState(),{name:'Maya',age:24,location:'Tokyo',occupation:'Creative technologist'});
  next={...next,styleMix:{influences:[{packId:'tech-girlie',weight:.7},{packId:'streetwear',weight:.3}],strength:.8,locks:{}},scene:{id:'cafe',name:'Café',location:'warm indoor coffee shop',activity:'conversation',ambience:'warm'},wardrobe:{source:'resolved',items:['Oversized charcoal hoodie','Silver headphones','Thin metal glasses'],locked:false},interestState:{characterInterests:['Programming','Photography','Reading','Travel'],activeContext:[]},dirty:false};
  return next;
}
let state=loadState();
let ui=loadUI();
let activeWorkspace=localStorage.getItem('promptforge-workspace')||'create';
let activeDrawer=null;
let previousFocus=null;
let generationSerial=0;
if(activeWorkspace==='style-packs')activeWorkspace='create';

function loadState(){try{const saved=localStorage.getItem(KEY);return saved?restoreState(saved):demoState()}catch{return demoState()}}
function loadUI(){try{return {focus:false,forge:'idle',busy:false,commandIndex:0,...JSON.parse(localStorage.getItem(UI_KEY)||'{}')}}catch{return {focus:false,forge:'idle',busy:false,commandIndex:0}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(UI_KEY,JSON.stringify({...ui,forge:'idle',busy:false}))}
function toast(message){const target=$('toast');target.textContent=message;target.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>target.classList.remove('show'),1800)}
function mutate(change,{clearTake=true}={}){state={...change(state),dirty:true,...(clearTake?{selectedTake:null}:{})};render()}
function setForge(mode){ui.forge=mode;const slot=$('forgeSlot');if(slot)slot.innerHTML=forgeOrbital(mode,mode==='generating'?'Forge constructing a Take':mode==='surprise'?'Forge creating a surprise':mode==='success'?'Take completed':mode==='error'?'Forge could not complete':'Forge idle')}

const SCENE_OPTIONS=[
  {id:'street',name:'City Street',location:'downtown city street',activity:'walking',ambience:'cool'},
  {id:'bedroom',name:'Bedroom',location:'quiet lived-in bedroom',activity:'reflecting',ambience:'warm'},
  {id:'cafe',name:'Café',location:'warm indoor coffee shop',activity:'conversation',ambience:'warm'},
  {id:'office',name:'Office',location:'modern creative office',activity:'working',ambience:'neutral'},
  {id:'forest',name:'Forest',location:'deep green woodland',activity:'exploring',ambience:'cool'},
  {id:'beach',name:'Beach',location:'open shoreline at golden hour',activity:'walking',ambience:'warm'},
  {id:'nightlife',name:'Nightlife',location:'rain-lit night district',activity:'meeting friends',ambience:'violet'},
  {id:'campus',name:'Campus',location:'university courtyard',activity:'between classes',ambience:'neutral'},
  {id:'studio',name:'Photo Studio',location:'minimal photography studio',activity:'posing',ambience:'neutral'},
  {id:'fantasy',name:'Fantasy Vale',location:'misty otherworldly valley',activity:'journeying',ambience:'violet'},
  {id:'sci-fi',name:'Orbital Station',location:'quiet orbital observation deck',activity:'observing',ambience:'cool'},
  {id:'library',name:'Library',location:'quiet library interior',activity:'reading',ambience:'warm'}
];

function ensureDrawer(id,title,eyebrow,intro,body){if($(id+'Drawer'))return;document.body.insertAdjacentHTML('beforeend',`<aside id="${id}Drawer" class="drawer" role="dialog" aria-hidden="true" aria-labelledby="${id}DrawerTitle"><button class="drawer-close" data-close-drawer aria-label="Close ${escape(title)}">×</button><div class="eyebrow">${escape(eyebrow)}</div><h2 id="${id}DrawerTitle">${escape(title)}</h2><p class="drawer-intro">${escape(intro)}</p>${body}</aside>`)}
function ensurePhotoDrawer(){ensureDrawer('photo','Direct the frame','PHOTOGRAPHY','Tune the camera language that carries through to every generated direction.','<form id="photoForm" class="drawer-form"><label>Shot type<select name="shotType"><option>Candid</option><option>Editorial portrait</option><option>Full body</option><option>Close-up</option></select></label><label>Lens<select name="lens"><option>35mm</option><option>50mm</option><option>85mm</option><option>105mm</option></select></label><label>Angle<select name="angle"><option>Eye level</option><option>Three-quarter</option><option>Low angle</option><option>High angle</option></select></label><label>Lighting<select name="behaviour"><option>Natural</option><option>Soft studio</option><option>Hard flash</option><option>Neon</option></select></label><label>Colour treatment<select name="colourTreatment"><option>Warm</option><option>Neutral</option><option>Cool</option><option>Monochrome</option></select></label><label class="lock-control"><input name="locked" type="checkbox"> Keep photography during generation</label><div class="drawer-actions"><button type="button" data-close-drawer>Cancel</button><button class="primary" type="submit">Save Photography</button></div></form>')}
function ensureSceneDrawer(){ensureDrawer('scene','Place the character','SCENE LIBRARY','Choose a setting and activity without leaving the Studio canvas.','<div id="sceneDrawerBody" class="scene-options"></div>')}
function ensureInterestsDrawer(){ensureDrawer('interests','Shape their inner world','INTERESTS','Interests influence personality, context and scene ideas.','<form id="interestsForm" class="drawer-form"><label>Interests <small>Separate interests with commas</small><textarea name="interests" rows="7"></textarea></label><div class="drawer-actions"><button type="button" data-close-drawer>Cancel</button><button class="primary" type="submit">Save Interests</button></div></form>')}

function setDrawer(name,open,origin){
  const drawer=$(name+'Drawer');if(!drawer)return;
  if(open&&activeDrawer&&activeDrawer!==name)setDrawer(activeDrawer,false);
  const overlay=$('overlay');activeDrawer=open?name:null;
  if(open){previousFocus=document.activeElement;const rect=origin?.getBoundingClientRect();if(rect)drawer.style.setProperty('--origin-y',`${rect.top+rect.height/2}px`)}
  drawer.classList.toggle('open',open);drawer.setAttribute('aria-hidden',String(!open));drawer.toggleAttribute('aria-modal',open);
  overlay.hidden=!open;overlay.classList.toggle('open',open);document.body.classList.toggle('drawer-open',open);
  if(open)requestAnimationFrame(()=>drawer.querySelector('input,button,textarea,select')?.focus());else previousFocus?.focus?.();
}
function closeDrawer(){if(activeDrawer)setDrawer(activeDrawer,false)}
function trapFocus(event,container){const focusable=[...container.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}

function renderReferenceList(){const status=$('coreReferenceStatus');let list=$('coreReferenceList');if(!list){list=document.createElement('div');list.id='coreReferenceList';list.className='reference-list';status.after(list)}list.innerHTML=(state.character?.references||[]).map((reference,index)=>`<span>Reference ${index+1} · ${escape(reference.source||'local')}</span>`).join('')||'<span>No references attached</span>'}
function openCore(origin){const character=state.character,form=$('coreForm');form.name.value=character?.name||'Maya';form.age.value=character?.identity?.age||24;form.location.value=character?.identity?.location||'Tokyo';form.occupation.value=character?.identity?.occupation||'Creative technologist';form.traits.value=(character?.personality?.traits||['curious','thoughtful']).join(', ');form.interests.value=(character?.interests||['programming','photography']).join(', ');$('coreReferenceStatus').textContent=character?.references?.length?`${character.references.length} reference${character.references.length===1?'':'s'} attached`:'No references attached';renderReferenceList();setDrawer('core',true,origin)}
function openPhoto(origin){ensurePhotoDrawer();const form=$('photoForm'),photo=state.visualSettings.photography,lighting=state.visualSettings.lighting;form.shotType.value=photo.shotType;form.lens.value=photo.lens;form.angle.value=photo.angle;form.behaviour.value=lighting.behaviour;form.colourTreatment.value=lighting.colourTreatment;form.locked.checked=photo.locked;setDrawer('photo',true,origin)}
function openInterests(origin){ensureInterestsDrawer();$('interestsForm').interests.value=state.interestState.characterInterests.join(', ');setDrawer('interests',true,origin)}

function renderSceneDrawer(){ensureSceneDrawer();$('sceneDrawerBody').innerHTML=SCENE_OPTIONS.map(scene=>`<button class="scene-option ${state.scene?.id===scene.id?'selected':''}" data-scene-id="${scene.id}"><i>${sceneGlyph(scene.id)}</i><b>${escape(scene.name)}</b><span>${escape(scene.location)}</span><small>${escape(scene.activity)}</small></button>`).join('')+'<button class="scene-option clear-scene" data-scene-id="clear"><i>×</i><b>No scene</b><span>Return to an unplaced character</span></button>';document.querySelectorAll('[data-scene-id]').forEach(button=>button.onclick=()=>{const id=button.dataset.sceneId;mutate(current=>({...current,scene:id==='clear'?null:SCENE_OPTIONS.find(scene=>scene.id===id)}));closeDrawer();toast(id==='clear'?'Scene cleared':'Scene selected')})}

function renderStyleDrawer(){
  const influenceMap=new Map((state.styleMix?.influences||[]).map(item=>[item.packId,item.weight]));
  const rows=STYLE_PACK_LIST.map(pack=>{const weight=influenceMap.get(pack.id)??50,active=influenceMap.has(pack.id);return `<article class="pack-row ${active?'active selected':''}" data-drawer-pack-row="${pack.id}"><label class="pack-choice"><input type="checkbox" data-drawer-pack-toggle="${pack.id}" ${active?'checked':''}><span><b>${escape(pack.name)}</b><small>${escape(pack.description)}</small></span></label><label class="pack-weight">Influence <output>${weight}%</output><input type="range" min="1" max="100" value="${weight}" data-drawer-pack-weight="${pack.id}" ${active?'':'disabled'}></label></article>`}).join('');
  $('styleDrawerBody').innerHTML=`<label class="pack-search"><span>Find a Style Pack</span><input id="drawerPackSearch" type="search" placeholder="Search ${STYLE_PACK_LIST.length} packs" autocomplete="off"></label><div class="pack-list drawer-pack-list">${rows}</div>`;
  $('drawerPackSearch').oninput=event=>{const query=event.target.value.toLowerCase();document.querySelectorAll('[data-drawer-pack-row]').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(query))};
  document.querySelectorAll('[data-drawer-pack-toggle]').forEach(input=>input.onchange=()=>{const id=input.dataset.drawerPackToggle;mutate(current=>{const influences=current.styleMix.influences.filter(item=>item.packId!==id);if(input.checked)influences.push({packId:id,weight:Number(document.querySelector(`[data-drawer-pack-weight="${id}"]`).value)});return {...current,styleMix:{...current.styleMix,influences}}});renderStyleDrawer();setDrawer('style',true)});
  document.querySelectorAll('[data-drawer-pack-weight]').forEach(input=>{input.oninput=()=>input.closest('label').querySelector('output').value=`${input.value}%`;input.onchange=()=>{const id=input.dataset.drawerPackWeight;mutate(current=>({...current,styleMix:{...current.styleMix,influences:current.styleMix.influences.map(item=>item.packId===id?{...item,weight:Number(input.value)}:item)}}));renderStyleDrawer();setDrawer('style',true)}});
}

function packDomains(packId){const pack=STYLE_PACK_LIST.find(item=>item.id===packId);return new Set(Object.keys(pack?.atoms||pack?.domains||{}).map(key=>({locations:'scene',visual:'photography',accessories:'wardrobe'}[key]||key)))}
function highlightInfluence(packId,on){const domains=packDomains(packId);document.querySelectorAll('[data-panel]').forEach(panel=>panel.classList.toggle('influenced',on&&domains.has(panel.dataset.panel)))}
function removePack(packId){mutate(current=>({...current,styleMix:{...current.styleMix,influences:current.styleMix.influences.filter(item=>item.packId!==packId)}}))}
function movePack(sourceId,targetId){if(sourceId===targetId)return;mutate(current=>{const list=[...current.styleMix.influences],source=list.findIndex(item=>item.packId===sourceId),target=list.findIndex(item=>item.packId===targetId);if(source<0||target<0)return current;const [item]=list.splice(source,1);list.splice(target,0,item);return {...current,styleMix:{...current.styleMix,influences:list}}})}
function renderStyleMix(){
  const influences=state.styleMix?.influences||[],total=influences.reduce((sum,item)=>sum+item.weight,0);
  const cards=influences.map(item=>{const pack=STYLE_PACK_LIST.find(candidate=>candidate.id===item.packId);if(!pack)return'';const percent=total?Math.round(item.weight/total*100):0;return `<article class="mix-card selected" draggable="true" data-mix-pack="${pack.id}" tabindex="0"><span class="pack-glyph">✦</span><div><b>${escape(pack.name)}</b><small>${percent}% influence</small></div><span class="mix-meter" style="--weight:${percent}%"></span><button data-remove-pack="${pack.id}" aria-label="Remove ${escape(pack.name)}">×</button></article>`}).join('');
  $('stylePanel').dataset.panel='style';$('stylePanel').classList.toggle('locked',!!state.generationOptions.keepStyleMix);$('stylePanel').innerHTML=`<h2>♧　Style Mix <span class="state-badge">${state.generationOptions.keepStyleMix?'Locked':'Live'}</span><button class="plus" id="browseStyleBtn" aria-label="Browse Style Packs">＋</button></h2><div class="mix-summary">${cards||'<div class="empty-copy">▱<b>No style packs selected</b><span>Choose influences to define your character\'s look.</span></div>'}</div><label class="strength">Style authority <output>${Math.round(state.styleMix.strength*100)}%</output><input id="styleStrength" type="range" min="0" max="100" value="${Math.round(state.styleMix.strength*100)}"></label><button class="wide" id="browseStyleBtnBottom">${cards?'Edit Style Mix':'Browse Style Packs'}　→</button>`;
  const open=event=>{renderStyleDrawer();setDrawer('style',true,event.currentTarget)};$('browseStyleBtn').onclick=open;$('browseStyleBtnBottom').onclick=open;
  $('styleStrength').oninput=event=>event.currentTarget.closest('label').querySelector('output').value=`${event.target.value}%`;$('styleStrength').onchange=event=>mutate(current=>({...current,styleMix:{...current.styleMix,strength:Number(event.target.value)/100}}));
  document.querySelectorAll('[data-remove-pack]').forEach(button=>button.onclick=()=>removePack(button.dataset.removePack));
  document.querySelectorAll('[data-mix-pack]').forEach(card=>{card.onmouseenter=()=>highlightInfluence(card.dataset.mixPack,true);card.onmouseleave=()=>highlightInfluence(card.dataset.mixPack,false);card.ondragstart=event=>event.dataTransfer.setData('text/plain',card.dataset.mixPack);card.ondragover=event=>event.preventDefault();card.ondrop=event=>{event.preventDefault();movePack(event.dataTransfer.getData('text/plain'),card.dataset.mixPack)}});
}

function whyThis(category){const data=state.resolvedDirectorState?.provenance?.categories?.[category],selection=data?.selection;if(!selection||selection.source!=='style-mix')return'';const chosen=data.candidates?.find(candidate=>candidate.id===selection.id);if(!chosen)return'';const sources=chosen.contributions?.map(item=>`${item.packName} ${Math.round(item.normalizedPackWeight*100)}%`).join(' · ');return sources?`<details class="why-this"><summary>Why this?</summary><p>Influenced by ${escape(sources)}.</p></details>`:''}
function selectedTake(){return state.takes.find(take=>take.id===state.selectedTake)||null}
function renderStage(){
  const has=!!state.character,art=$('stage').querySelector('.stage-art'),activeTake=selectedTake();
  $('stage').classList.toggle('selected',!!activeTake);$('stage').classList.remove('stage-refresh');void $('stage').offsetWidth;$('stage').classList.add('stage-refresh');
  if(!has)art.innerHTML=`<div class="forge-slot" id="forgeSlot"></div><span>NO CHARACTER YET</span><strong>Let’s create<br>someone new.</strong><p>Start from scratch, use a quick generator,<br>or jump in and build manually.</p><button class="primary" id="createBtn">✦　Create New Character</button><button id="surpriseBtn">◈　Surprise Me</button><button id="importBtn">□　Import Character (JSON)</button>${editorialNote('Every character has a first take.','arrow')}`;
  else{const snap=activeTake?.stateSnapshot,photo=snap?.visualSettings?.photography||state.visualSettings.photography,expression=snap?.visualSettings?.expression||state.visualSettings.expression,scene=snap?.scene||state.scene;art.innerHTML=`<div class="portrait-frame"><img src="${MAYA_PORTRAIT}" alt="${escape(state.character.name)} in a warm cafe"/><div class="portrait-shade"></div><div class="portrait-identity"><span>${activeTake?`TAKE ${String(state.takes.indexOf(activeTake)+1).padStart(2,'0')}`:'ACTIVE CHARACTER'}</span><strong>${escape(state.character.name)}</strong><p>${state.character.identity.age} · ${escape(state.character.identity.location)}<br>${escape(state.character.identity.occupation)}</p></div><button class="image-action" id="imageReferenceBtn">↗</button><button class="image-action image-more" id="imageMoreBtn">•••</button></div><div class="stage-direction"><span>${escape(photo.shotType)} · ${escape(photo.lens)}</span><span>${escape(expression.expression)}</span><span>${escape(scene?.name||'Unplaced')}</span></div><div class="stage-actions"><button class="primary" id="stageCompile">✦ Compile Prompt</button><button id="newTakeBtn">＋ New Take</button><button id="characterEditStage">Edit Identity</button></div><small>Reference image · Stable ID ${escape(state.character.id)} · Revision ${state.character.revision}</small>${editorialNote(activeTake?'There she is.':'Good ideas need a place to land.','underline')}`}
  setForge(ui.forge);
  if(!has){$('createBtn').onclick=event=>openCore(event.currentTarget);$('surpriseBtn').onclick=()=>surprise();$('importBtn').onclick=()=>$('importFile').click()}else{$('stageCompile').onclick=compileOnly;$('newTakeBtn').onclick=()=>runGeneration('new-take');$('characterEditStage').onclick=event=>openCore(event.currentTarget);$('imageReferenceBtn').onclick=()=>toast('Reference image is active for Maya');$('imageMoreBtn').onclick=event=>openPhoto(event.currentTarget)}
}

function renderTakes(){
  $('takeCount').textContent=state.takes.length;$('takesEmpty').style.display=state.takes.length?'none':'flex';
  $('takesList').innerHTML=state.takes.map((take,index)=>{const snap=take.stateSnapshot,photo=snap?.visualSettings?.photography||{},scene=snap?.scene;return `<button class="take ${take.id===state.selectedTake?'selected':''}" data-take="${escape(take.id)}" aria-pressed="${take.id===state.selectedTake}"><span class="take-frame"><i>${sceneGlyph(scene?.id)}</i><em>${escape(photo.lens||'—')}</em></span><b>Take ${String(index+1).padStart(2,'0')}</b><small>${escape(scene?.name||photo.shotType||'Character study')}</small></button>`}).join('');
  document.querySelectorAll('[data-take]').forEach(button=>button.onclick=()=>{state=promoteTake(state,button.dataset.take);render();button.scrollIntoView({behavior:motionOK()?'smooth':'auto',inline:'center',block:'nearest'})});
}

function renderGenerationOptions(){
  const options=state.generationOptions,disabled=!state.character,panel=document.querySelector('.generation .panel:first-child');panel.dataset.panel='generation';
  panel.innerHTML=`<h2>✣　Generation Options <span class="state-badge">${ui.busy?'Building':'Ready'}</span></h2><div class="toggles"><label>Keep character <input type="checkbox" checked disabled></label><label>Keep style mix <input data-option="keepStyleMix" type="checkbox" ${options.keepStyleMix?'checked':''} ${disabled?'disabled':''}></label><label>Keep scene <input data-option="keepScene" type="checkbox" ${options.keepScene?'checked':''} ${disabled?'disabled':''}></label><label>New pose & expression <input data-option="newPose" type="checkbox" ${options.newPose?'checked':''} ${disabled?'disabled':''}></label><label>New wardrobe <input data-option="newWardrobe" type="checkbox" ${options.newWardrobe?'checked':''} ${disabled?'disabled':''}></label></div><button class="primary wide" id="generateBtn" ${disabled||ui.busy?'disabled':''}>${ui.busy?'Constructing…':'✦　Generate Take'}</button>`;
  document.querySelectorAll('[data-option]').forEach(input=>input.onchange=event=>mutate(current=>({...current,generationOptions:{...current.generationOptions,[event.target.dataset.option]:event.target.checked}}),{clearTake:false}));
  $('generateBtn').onclick=()=>runGeneration('generate');
}

function renderLighting(){const panel=document.querySelector('.generation .panel:nth-child(2)');panel.dataset.panel='lighting';panel.innerHTML=`<h2>☼　Lighting & Atmosphere</h2>${state.scene?`<div class="control-summary"><b>${escape(state.visualSettings.lighting.behaviour)}</b><br><small>${escape(state.visualSettings.lighting.colourTreatment)} treatment · ${escape(state.scene.name)}</small></div>`:'<div class="disabled-copy">No environment settings<span>Lighting and weather controls will be available after selecting a scene.</span></div>'}`}
function renderDependents(){
  const panels=[...document.querySelectorAll('.expression .dependent')];panels[0].dataset.panel='appearance';panels[1].dataset.panel='wardrobe';panels[2].dataset.panel='photography';
  if(!state.character){panels.forEach(panel=>panel.classList.add('disabled'));return}
  panels.forEach(panel=>panel.classList.remove('disabled'));const appearance=state.character.appearance;
  panels[0].dataset.panel='expression';panels[0].classList.toggle('locked',!state.generationOptions.newPose);panels[0].innerHTML=`<h2>♙　Appearance <span class="state-badge locked">Core locked</span><button class="edit-link" id="characterEdit">Edit Core</button></h2><div class="field-grid"><span>Hair<br><b>${escape(appearance.hair.colour)}, ${escape(appearance.hair.style)}</b></span><span>Skin<br><b>${escape(appearance.skinDetails.join(', '))}</b></span></div><div class="expression-direction"><small>Current direction</small><b>${escape(state.visualSettings.expression.pose)} · ${escape(state.visualSettings.expression.expression)}</b></div>`;
  panels[1].classList.toggle('locked',state.wardrobe.locked||!state.generationOptions.newWardrobe);panels[1].innerHTML=`<h2>♧　Wardrobe <span class="state-badge">${state.wardrobe.locked||!state.generationOptions.newWardrobe?'Locked':'Resolved'}</span><button class="edit-link" id="wardrobeEdit">Manual</button></h2><div class="wardrobe-thumbs"><i>🧥</i><i>🎧</i><i>👓</i></div><div class="control-summary">${escape(state.wardrobe.items.join(' · ')||state.resolvedDirectorState?.resolved?.wardrobe?.join?.(' · ')||'Resolved from Style Mix')}</div><label class="lock-control"><input id="wardrobeLock" type="checkbox" ${state.wardrobe.locked?'checked':''}> Keep manual wardrobe</label>${whyThis('wardrobe')}`;
  const photo=state.visualSettings.photography;panels[2].classList.toggle('locked',photo.locked);panels[2].innerHTML=`<h2>▣　Photography <span class="state-badge">${photo.locked?'Locked':'Live'}</span><button class="edit-link" id="photoEdit">Edit</button></h2><div class="control-summary">${escape(photo.shotType)} · ${escape(photo.lens)} · ${escape(photo.angle)}<br><small>${escape(state.visualSettings.lighting.behaviour)} · ${escape(state.visualSettings.lighting.colourTreatment)}</small></div>${whyThis('photography')}`;
  $('characterEdit').onclick=event=>openCore(event.currentTarget);$('wardrobeEdit').onclick=event=>{const form=$('wardrobeForm');form.items.value=state.wardrobe.items.join(', ');form.locked.checked=state.wardrobe.locked;setDrawer('wardrobe',true,event.currentTarget)};$('photoEdit').onclick=event=>openPhoto(event.currentTarget);$('wardrobeLock').onchange=event=>mutate(current=>({...current,wardrobe:{...current.wardrobe,locked:event.target.checked}}));
}

function renderContext(){const interestPanel=$('interestText').closest('.panel'),scenePanel=$('sceneText').closest('.panel');interestPanel.dataset.panel='interests';scenePanel.dataset.panel='scene';scenePanel.classList.toggle('locked',!!state.generationOptions.keepScene);$('interestText').textContent=state.interestState.characterInterests.join(' · ')||'No interests selected';$('sceneText').textContent=state.scene?.name||'No scene selected';$('interestBtn').onclick=event=>openInterests(event.currentTarget);$('sceneBtn').onclick=event=>{renderSceneDrawer();setDrawer('scene',true,event.currentTarget)}}
function applyAmbience(){const ambience=state.scene?.ambience||(state.visualSettings.lighting.colourTreatment==='Warm'?'warm':state.visualSettings.lighting.colourTreatment==='Cool'?'cool':'neutral');document.body.dataset.ambience=ambience;document.body.classList.toggle('focus-mode',ui.focus);$('focusBtn').setAttribute('aria-pressed',String(ui.focus));$('focusBtn').textContent=ui.focus?'◎ Exit Focus':'◎ Focus'}

function render(){
  renderWorkspaceShell();if(activeWorkspace!=='create'){renderWorkspaceView();bindGlobal();save();return}
  const has=!!state.character;$('studioTitle').textContent=has?state.character.name:'Create Something Extraordinary';$('studioSubtitle').textContent=has?`${state.character.identity.occupation} · ${state.character.identity.location}${state.dirty?' · Working changes':''}`:'Build characters. Style their world. Generate infinite possibilities.';
  renderStyleMix();renderContext();renderStage();renderDependents();renderGenerationOptions();renderLighting();renderTakes();applyAmbience();bindGlobal();save();
}

const workspaceMeta={characters:['Characters','Saved Character Cores','Manage identity foundations without changing the active Studio.'],scenes:['Scenes','Scene library','Reusable settings for future directing sessions.'],library:['Library','Content library','Browse and shape the reusable content behind your characters.'],projects:['Projects','Workspace shell','Group Characters, Scenes, Takes, and references.'],inspiration:['Inspiration','Coming soon','A deliberate home for reference boards and visual direction.'],tools:['Tools','Power tools','Diagnostics and developer utilities for the current session.'],settings:['Settings','Preferences','Storage and compiler preferences will live here.']};
function renderWorkspaceShell(){const root=$('workspaceRoot');root.querySelector('.workspace-view')?.remove();root.querySelector('.studio-head').classList.toggle('hidden',activeWorkspace!=='create');document.querySelectorAll('[data-workspace]').forEach(button=>{const active=button.dataset.workspace===activeWorkspace;button.classList.toggle('nav-active',active);if(button.closest('.topbar'))button.classList.toggle('active',active);button.toggleAttribute('aria-current',active)});if(activeWorkspace!=='create')root.querySelectorAll(':scope > *:not(.workspace-view):not(.studio-head)').forEach(node=>node.classList.add('hidden'));else root.querySelectorAll(':scope > *').forEach(node=>node.classList.remove('hidden'))}
function renderWorkspaceView(){const root=$('workspaceRoot'),view=document.createElement('div');view.className='workspace-view';const meta=workspaceMeta[activeWorkspace]||workspaceMeta.projects;let body='';if(activeWorkspace==='characters')body=state.character?`<article class="panel"><h2>${escape(state.character.name)}</h2><p>${escape(state.character.identity.occupation)} · ${escape(state.character.identity.location)}</p><small>Stable ID ${escape(state.character.id)} · Revision ${state.character.revision}</small></article>`:'<div class="empty-copy"><b>No saved Characters yet</b><span>Create a Character Core in Create to see it here.</span></div>';else if(activeWorkspace==='scenes')body=`<div class="workspace-grid">${SCENE_OPTIONS.map(scene=>`<article class="panel catalogue-card"><h2>${sceneGlyph(scene.id)} ${escape(scene.name)}</h2><p>${escape(scene.location)}</p><small>${escape(scene.activity)}</small></article>`).join('')}</div>`;else if(activeWorkspace==='library'){root.append(view);renderLibraryWorkspace(view);return}else if(activeWorkspace==='tools')body='<div class="panel"><h2>Resolver Inspector</h2><p>Inspect deterministic Style resolution in Create.</p><button class="primary" id="toolsInspect">Open Inspector</button></div>';else body=`<div class="panel"><h2>${meta[0]}</h2><p>${meta[2]}</p><div class="empty-copy"><b>${meta[1]} is ready for the next milestone</b><span>This workspace keeps your Studio state intact.</span></div></div>`;view.innerHTML=`<div class="studio-head"><div class="eyebrow">PROMPTFORGE WORKSPACE</div><h1>${meta[0]}</h1><p>${meta[2]}</p></div>${body}`;root.append(view);$('toolsInspect')?.addEventListener('click',()=>{goWorkspace('create');setTimeout(inspect,0)})}

const coverageLabel=status=>({poor:'Needs content',low:'Early',good:'Growing',healthy:'Healthy'}[status]||status);
function libraryRegistry(){const registry=createLibraryRegistry({stylePacks:STYLE_PACK_LIST,scenes:SCENE_OPTIONS,state});validateLibraryRegistry(registry);return registry}
function selectedLibrary(registry){let category=registry.find(item=>item.id===(ui.libraryCategory||'interests'))||registry[0];let family=category.families.find(item=>item.id===ui.libraryFamily)||category.families[0]||null;return {category,family}}
function libraryCount(category){return `${category.entryCount} ${category.entryCount===1?'entry':'entries'}`}
function librarySource(family){if(family.fixture)return 'Starter structure';const sources=[...new Set((family.entries||[]).map(entry=>entry.source))];return sources.length===1?`${sources[0][0].toUpperCase()}${sources[0].slice(1)} content`:'Mixed sources'}
function renderLibraryWorkspace(view){
  const registry=libraryRegistry(),filter=ui.libraryFilter||'all',query=ui.libraryQuery||'',results=searchLibrary(registry,query,filter);let {category,family}=selectedLibrary(registry);
  if(!results.some(item=>item.id===category.id)){category=results[0]||category;family=category.families[0]||null}
  const allEntries=registry.reduce((sum,item)=>sum+item.entryCount,0),starterCount=registry.flatMap(item=>item.families).filter(item=>item.fixture).length,focusCoverage=['interests','hobbies'].map(id=>{const report=coverageDiagnostics(registry,id);return `${id[0].toUpperCase()+id.slice(1)} ${coverageLabel(report.category)}`}).join(' · ');
  const categoryRows=registry.filter(item=>filter==='all'||item.id===filter).map(item=>`<button class="library-category ${item.id===category.id?'selected':''}" data-library-category="${item.id}" aria-pressed="${item.id===category.id}"><span class="library-icon">${escape(item.icon)}</span><span><b>${escape(item.label)}</b><small>${libraryCount(item)} · ${item.familyCount} ${item.familyCount===1?'family':'families'}</small></span><em class="coverage-dot ${item.coverage}" title="${coverageLabel(item.coverage)}"></em></button>`).join('');
  const families=(results.find(item=>item.id===category.id)?.families||[]).map(item=>{const coverage=coverageFor(item.entries.length);return `<button class="library-family ${family?.id===item.id?'selected':''}" data-library-family="${item.id}" aria-pressed="${family?.id===item.id}"><span class="family-glyph">${escape(category.icon)}</span><span class="family-title"><b>${escape(item.label)}</b><small>${item.entries.length} ${item.entries.length===1?'entry':'entries'}</small></span><p>${escape(item.description)}</p><span class="family-foot"><small>${escape(librarySource(item))}</small><em class="coverage-label ${coverage}">${coverageLabel(coverage)}</em></span></button>`}).join('');
  view.innerHTML=`<header class="library-head"><div><div class="eyebrow">CONTENT FOUNDATION · SCHEMA ${LIBRARY_SCHEMA_VERSION}</div><h1>▤ Library</h1><p>Reusable character, world and expression content—kept clear by source.</p></div><div class="library-head-actions"><button id="libraryExport">Export manifest</button><button id="libraryImport">Import preview</button><input id="libraryImportFile" type="file" accept="application/json" hidden></div></header><div class="library-toolbar"><label class="library-search"><span>⌕</span><input id="librarySearch" type="search" value="${escape(query)}" placeholder="Search categories, families and entries" autocomplete="off"></label><label class="library-filter"><span class="sr-only">Category filter</span><select id="libraryFilter"><option value="all">All categories</option>${registry.map(item=>`<option value="${item.id}" ${filter===item.id?'selected':''}>${escape(item.label)}</option>`).join('')}</select></label><span class="library-total">${allEntries} wired entries · ${focusCoverage}</span></div><div class="library-layout"><aside class="library-categories" aria-label="Library categories"><div class="library-pane-title"><b>Content categories</b><small>${registry.length} domains</small></div>${categoryRows}</aside><section class="library-browser"><header class="library-browser-head"><div><span class="library-kicker">${escape(category.layer==='starter'?'STARTER FOUNDATION':category.layer.toUpperCase())}</span><h2>${escape(category.icon)} ${escape(category.label)}</h2><p>${escape(category.description)}</p></div><span class="coverage-chip ${category.coverage}">${coverageLabel(category.coverage)}</span></header><div class="library-subnav"><b>Families</b><span>${category.familyCount} groups · ${libraryCount(category)}</span></div><div class="library-families">${families||`<div class="library-empty"><b>No matching content</b><span>Try a broader search or another category.</span></div>`}</div></section><aside class="library-detail" aria-live="polite">${renderLibraryDetail(category,family)}</aside></div>`;
  bindLibraryWorkspace(registry,category,family);
}
function renderLibraryDetail(category,family){if(!family)return '<div class="library-empty"><b>Select a family</b><span>Details and entries will appear here.</span></div>';const tab=ui.libraryTab||'overview',entries=family.entries||[],subcategories=family.subcategories||[];const tabs=['overview','entries','related'];let content='';if(tab==='entries')content=entries.length?`<div class="library-entry-list">${entries.map(entry=>`<div><span>${escape(entry.label)}</span><small>${escape(entry.source)}</small></div>`).join('')}</div>`:'<div class="library-empty compact"><b>No entries yet</b><span>This family is ready for content enrichment.</span></div>';else if(tab==='related')content=`<div class="detail-copy"><p>Links are soft context only: they can inform recommendations without forcing a hobby onto a character.</p><div class="detail-tags">${(family.tags||[]).map(tag=>`<span>${escape(tag)}</span>`).join('')||'<span>Unmapped</span>'}</div></div>`;else content=`<div class="detail-copy"><p>${escape(family.description)}</p><div class="detail-tags">${[...(family.tags||[]),librarySource(family)].map(tag=>`<span>${escape(tag)}</span>`).join('')}</div></div>${subcategories.length?`<section class="subcategory-section"><header><b>Subcategories</b><small>${subcategories.length}</small></header>${subcategories.map(row=>`<div><span>${escape(row.label)}</span><small>${row.entryCount} ${row.entryCount===1?'entry':'entries'}</small></div>`).join('')}</section>`:''}`;return `<header class="detail-head"><span class="detail-icon">${escape(category.icon)}</span><div><span class="library-kicker">${family.fixture?'STARTER STRUCTURE':'LIVE CONTENT'}</span><h2>${escape(family.label)}</h2><p>${entries.length} ${entries.length===1?'entry':'entries'} · ${escape(librarySource(family))}</p></div></header><div class="detail-tabs" role="tablist">${tabs.map(name=>`<button role="tab" aria-selected="${tab===name}" data-library-tab="${name}">${name[0].toUpperCase()+name.slice(1)}${name==='entries'?` (${entries.length})`:''}</button>`).join('')}</div>${content}<section class="gemini-foundation"><div><span>✦</span><b>Enrichment operations</b><p>Prepare structured candidates for review; core data is never mutated.</p></div><select id="libraryExpandMode" aria-label="Enrichment operation">${ENRICHMENT_OPERATIONS.map(name=>`<option>${name}</option>`).join('')}</select><button id="libraryExpand">Prepare review</button></section><footer class="detail-provenance"><span>Source layers</span><b>core + user + imported/generated review</b></footer>`}
function bindLibraryWorkspace(registry,category,family){
  document.querySelectorAll('[data-library-category]').forEach(button=>button.onclick=()=>{ui.libraryCategory=button.dataset.libraryCategory;ui.libraryFamily=null;ui.libraryTab='overview';render()});document.querySelectorAll('[data-library-family]').forEach(button=>button.onclick=()=>{ui.libraryCategory=category.id;ui.libraryFamily=button.dataset.libraryFamily;ui.libraryTab='overview';render()});document.querySelectorAll('[data-library-tab]').forEach(button=>button.onclick=()=>{ui.libraryTab=button.dataset.libraryTab;render()});
  $('librarySearch').oninput=event=>{ui.libraryQuery=event.target.value;const caret=event.target.selectionStart;render();requestAnimationFrame(()=>{const input=$('librarySearch');input.focus();input.setSelectionRange(caret,caret)})};$('libraryFilter').onchange=event=>{ui.libraryFilter=event.target.value;ui.libraryCategory=event.target.value==='all'?ui.libraryCategory:event.target.value;ui.libraryFamily=null;render()};
  $('libraryExpand')?.addEventListener('click',()=>{const prepared=prepareEnrichmentOperation($('libraryExpandMode').value,category.id,family?.id,registry);toast(`${prepared.operation} prepared for review—core library unchanged`)});$('libraryExport').onclick=()=>exportLibraryManifest(registry);$('libraryImport').onclick=()=>$('libraryImportFile').click();$('libraryImportFile').onchange=event=>previewLibraryImport(event.target.files[0]);
}
function exportLibraryManifest(registry){const payload={schemaVersion:LIBRARY_SCHEMA_VERSION,exportedAt:new Date().toISOString(),mode:'layered-manifest',categories:registry};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='promptforge-library-manifest.json';link.click();URL.revokeObjectURL(url);toast('Library manifest exported')}
async function previewLibraryImport(file){if(!file)return;try{const parsed=JSON.parse(await file.text());if(!parsed.schemaVersion||!Array.isArray(parsed.categories))throw new Error('invalid');toast('Import preview validated—nothing was merged')}catch{toast('That file is not a PromptForge Library manifest')}finally{$('libraryImportFile').value=''}}
function goWorkspace(name){activeWorkspace=name;localStorage.setItem('promptforge-workspace',name);render()}

function inspectorPayload(resolved){return {resolver:resolved.resolver,normalizedMix:resolved.styleMix.normalizedInfluences,resolved:resolved.resolved,provenance:Object.fromEntries(Object.entries(resolved.provenance.categories).map(([category,data])=>[category,{selection:data.selection,candidates:data.candidates.map(candidate=>({id:candidate.id,score:candidate.score,support:candidate.support,seedFactor:candidate.seedFactor,contributors:candidate.contributions.map(item=>item.packName),adjustments:candidate.adjustments}))}]))}}
function inspect(){if(!state.character){toast('Create a Character Core before resolving');return}try{const resolved=resolveStudioState(state),output=JSON.stringify(inspectorPayload(resolved),null,2);$('inspectorOutput').textContent=output;$('drawerInspectorOutput').textContent=output;setDrawer('inspector',true,$('inspectBtn'))}catch(error){toast(error.message)}}
function showConsole(){const panel=$('console');panel.classList.remove('hidden');panel.innerHTML='✓ Character Core preserved<br>✓ Style Mix normalized and resolved<br>✓ Context compatibility scored<br>✓ Locks and overrides applied<br><br>✨ Resolver output forwarded to MockCompiler<br>✓ Master Director Prompt ready'}
function compileOnly(){if(!state.character){toast('Create a Character Core before compiling');return}try{setForge('generating');state=compilePrompt(state,MockCompiler);showConsole();render();setForge('success');setTimeout(()=>setForge('idle'),motionOK()?420:0);toast('Master Director Prompt ready')}catch(error){setForge('error');toast(error.message)}}

async function runGeneration(kind='generate'){
  if(!state.character){toast('Create a Character Core first');return}const serial=++generationSerial;ui.busy=true;ui.forge=kind==='surprise'?'surprise':'generating';
  try{state={...state,generationOptions:{...state.generationOptions,seed:`promptforge-take-${state.takes.length+1}`}};state=compileGeneration(state,MockCompiler);state=createTake(state,kind);render();showConsole();const sequence=['identity','expression','interests','wardrobe','scene','photography','lighting','generation'];for(const name of sequence){if(serial!==generationSerial)return;const panel=document.querySelector(`[data-panel="${name}"]`);if(!panel||panel.classList.contains('locked'))continue;panel.classList.add('updating');panel.setAttribute('aria-busy','true');if(motionOK())await wait(85);panel.classList.remove('updating');panel.removeAttribute('aria-busy')}ui.forge='success';setForge('success');ui.busy=false;renderGenerationOptions();if(motionOK())await wait(420);if(serial===generationSerial){ui.forge='idle';setForge('idle')}toast(kind==='surprise'?'A surprising new Take is ready':'New Take ready')}
  catch(error){ui.busy=false;ui.forge='error';setForge('error');toast(error.message)}
}
function surprise(){const index=state.takes.length;if(!state.character)state=createCharacter(state,{name:['Nova','Maya','Ari','Sora'][index%4],location:['Tokyo','London','Seoul','New York'][index%4],occupation:['Creative technologist','Editorial photographer','Architect','Indie designer'][index%4]});const options=state.generationOptions;if(!options.keepStyleMix){const a=STYLE_PACK_LIST[index%STYLE_PACK_LIST.length],b=STYLE_PACK_LIST[(index+5)%STYLE_PACK_LIST.length];state={...state,styleMix:{...state.styleMix,influences:[{packId:a.id,weight:65},{packId:b.id,weight:35}]}}}if(!options.keepScene)state={...state,scene:SCENE_OPTIONS[(index*3+2)%SCENE_OPTIONS.length]};runGeneration('surprise')}

function commandItems(){const base=[{label:'Create or edit character',group:'Character',run:()=>openCore($('commandTrigger'))},{label:'Generate Take',group:'Forge',disabled:!state.character,run:()=>runGeneration('generate')},{label:'Surprise Me',group:'Forge',run:surprise},{label:'Open Style Mix',group:'Studio',run:()=>{renderStyleDrawer();setDrawer('style',true,$('stylePanel'))}},{label:'Open Scene browser',group:'Studio',run:()=>{renderSceneDrawer();setDrawer('scene',true,$('sceneBtn'))}},{label:'Open Takes',group:'Studio',run:()=>{$('takesList').scrollIntoView({behavior:motionOK()?'smooth':'auto'})}},{label:'Inspect resolution',group:'Tools',disabled:!state.character,run:inspect},{label:ui.focus?'Exit Focus Mode':'Enter Focus Mode',group:'View',disabled:!state.character,run:toggleFocus},{label:'Import Character',group:'Character',run:()=>$('importFile').click()},{label:'Export Character',group:'Character',disabled:!state.character,run:exportCharacter},{label:'Open Settings',group:'Navigate',run:()=>goWorkspace('settings')}];const packs=STYLE_PACK_LIST.map(pack=>({label:pack.name,group:'Style Pack',run:()=>{renderStyleDrawer();setDrawer('style',true,$('stylePanel'));requestAnimationFrame(()=>{const input=$('drawerPackSearch');input.value=pack.name;input.dispatchEvent(new Event('input'))})}}));const scenes=SCENE_OPTIONS.map(scene=>({label:scene.name,group:'Scene',run:()=>{state={...state,scene};render();toast(`${scene.name} selected`)}}));return [...base,...packs,...scenes]}
function openCommand(){closeDrawer();const palette=$('commandPalette');previousFocus=document.activeElement;palette.hidden=false;document.body.classList.add('command-open');$('commandInput').value='';ui.commandIndex=0;renderCommands();requestAnimationFrame(()=>$('commandInput').focus())}
function closeCommand(){const palette=$('commandPalette');if(palette.hidden)return;palette.hidden=true;document.body.classList.remove('command-open');previousFocus?.focus?.()}
function filteredCommands(){const query=$('commandInput').value.trim().toLowerCase();return commandItems().filter(item=>!query||`${item.label} ${item.group}`.toLowerCase().includes(query))}
function renderCommands(){const items=filteredCommands();ui.commandIndex=Math.max(0,Math.min(ui.commandIndex,items.length-1));$('commandResults').innerHTML=items.length?items.map((item,index)=>`<button role="option" aria-selected="${index===ui.commandIndex}" class="command-item ${index===ui.commandIndex?'active':''}" data-command-index="${index}" ${item.disabled?'disabled':''}><span>${escape(item.label)}</span><small>${escape(item.group)}</small></button>`).join(''):'<p class="command-empty">No matching command.</p>';document.querySelectorAll('[data-command-index]').forEach(button=>button.onclick=()=>executeCommand(Number(button.dataset.commandIndex)))}
function executeCommand(index=ui.commandIndex){const item=filteredCommands()[index];if(!item||item.disabled)return;closeCommand();item.run()}
function toggleFocus(){if(!state.character){toast('Create a character before entering Focus Mode');return}ui.focus=!ui.focus;applyAmbience();save();toast(ui.focus?'Focus Mode on':'Focus Mode off')}
function exportCharacter(){if(!state.character)return;const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${state.character.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'character'}.json`;link.click();URL.revokeObjectURL(url);toast('Character exported')}
async function importCharacter(file){try{const parsed=JSON.parse(await file.text());state=parsed.character?restoreState(JSON.stringify(parsed)):createCharacter(blankState(),parsed);goWorkspace('create');toast('Character imported')}catch{toast('That file is not a valid PromptForge character')}}

function bindGlobal(){
  ensureSceneDrawer();ensurePhotoDrawer();ensureInterestsDrawer();document.querySelectorAll('[data-close-drawer]').forEach(button=>button.onclick=closeDrawer);$('overlay').onclick=closeDrawer;
  $('coreReferenceBtn').onclick=()=>{if(!state.character){toast('Save the Character Core first');return}state=addReference(state,{source:`mock-local-${state.character.references.length+1}`});$('coreReferenceStatus').textContent=`${state.character.references.length} reference${state.character.references.length===1?'':'s'} attached`;renderReferenceList();save();toast('Reference attached')};
  $('wardrobeForm').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget),items=String(data.get('items')||'').split(',').map(item=>item.trim()).filter(Boolean);state={...state,wardrobe:{...state.wardrobe,source:'manual',items,locked:data.get('locked')==='on'},dirty:true,selectedTake:null};closeDrawer();render();toast('Wardrobe saved')};
  $('photoForm').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget);state={...state,visualSettings:{...state.visualSettings,photography:{...state.visualSettings.photography,shotType:String(data.get('shotType')),lens:String(data.get('lens')),angle:String(data.get('angle')),locked:data.get('locked')==='on'},lighting:{...state.visualSettings.lighting,behaviour:String(data.get('behaviour')),colourTreatment:String(data.get('colourTreatment'))}},dirty:true,selectedTake:null};closeDrawer();render();toast('Photography saved')};
  $('interestsForm').onsubmit=event=>{event.preventDefault();const interests=String(new FormData(event.currentTarget).get('interests')||'').split(',').map(item=>item.trim()).filter(Boolean);state={...state,interestState:{...state.interestState,characterInterests:interests},character:state.character?{...state.character,interests}:state.character,dirty:true,selectedTake:null};closeDrawer();render();toast('Interests saved')};
  $('coreForm').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget),list=name=>String(data.get(name)||'').split(',').map(item=>item.trim()).filter(Boolean),input={name:String(data.get('name')).trim(),age:Number(data.get('age')),location:String(data.get('location')).trim(),occupation:String(data.get('occupation')).trim()};const next=state.character?editCharacter(state,input):createCharacter(state,input);state={...next,character:{...next.character,personality:{...next.character.personality,traits:list('traits')},interests:list('interests')},interestState:{...next.interestState,characterInterests:list('interests')}};closeDrawer();render();toast('Character Core saved')};
  document.querySelectorAll('[data-workspace]').forEach(button=>button.onclick=()=>{if(button.dataset.workspace==='style-packs'){goWorkspace('create');renderStyleDrawer();setDrawer('style',true,button)}else goWorkspace(button.dataset.workspace)});
  $('compileBtn').onclick=compileOnly;$('inspectBtn').onclick=inspect;$('seedInput').value=state.generationOptions.seed;$('seedInput').onchange=event=>mutate(current=>({...current,generationOptions:{...current.generationOptions,seed:event.target.value||'promptforge-1'}}),{clearTake:false});
  $('commandTrigger').onclick=openCommand;$('focusBtn').onclick=toggleFocus;$('commandInput').oninput=()=>{ui.commandIndex=0;renderCommands()};$('importFile').onchange=event=>{const file=event.target.files[0];if(file)importCharacter(file);event.target.value=''};
}

document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();$('commandPalette').hidden?openCommand():closeCommand();return}if(!$('commandPalette').hidden){if(event.key==='Escape'){event.preventDefault();closeCommand()}else if(event.key==='ArrowDown'){event.preventDefault();ui.commandIndex=Math.min(ui.commandIndex+1,filteredCommands().length-1);renderCommands()}else if(event.key==='ArrowUp'){event.preventDefault();ui.commandIndex=Math.max(ui.commandIndex-1,0);renderCommands()}else if(event.key==='Enter'){event.preventDefault();executeCommand()}else if(event.key==='Tab')trapFocus(event,$('commandPalette'));return}if(activeDrawer){if(event.key==='Escape'){event.preventDefault();closeDrawer()}else if(event.key==='Tab')trapFocus(event,$(activeDrawer+'Drawer'))}});
document.addEventListener('visibilitychange',()=>document.documentElement.toggleAttribute('data-page-hidden',document.hidden));
render();
