const clone=value=>structuredClone(value);
export const STAGE_MODES=Object.freeze(['empty','core-ready','reference','take']);
export const blankState=()=>({character:null,styleMix:{influences:[],strength:.8},interestState:{characterInterests:[],activeContext:[]},scene:null,wardrobe:{source:'resolved',items:[],locked:false},visualSettings:{photography:{shotType:'Candid',lens:'50mm',angle:'Eye level'},lighting:{behaviour:'Natural',colourTreatment:'Warm'}},generationOptions:{},selectedTake:null,takes:[],compiledPrompts:[],dirty:false});
export function stageMode(state){if(!state.character)return 'empty';if(state.selectedTake&&state.takes.some(t=>t.id===state.selectedTake))return 'take';if(state.character.references?.length)return 'reference';return 'core-ready'}
export function createCharacter(state,input){const existing=state.character;const character={id:existing?.id||input.id||`character_${Date.now()}`,name:input.name||existing?.name||'Maya',identity:{age:Number(input.age)||existing?.identity?.age||24,location:input.location||existing?.identity?.location||'Tokyo',occupation:input.occupation||existing?.identity?.occupation||'Creative technologist'},appearance:existing?.appearance||{facialStructure:['soft oval'],facialFeatures:['brown almond eyes'],skinDetails:['natural complexion'],hair:{colour:'dark brown',style:'messy bun'},signatureFeatures:['silver necklace']},personality:existing?.personality||{traits:['curious','thoughtful']},interests:existing?.interests||['programming','photography'],references:existing?.references||[],locks:existing?.locks||{identity:true,appearance:true},revision:(existing?.revision||0)+1};return {...state,character,interestState:{...state.interestState,characterInterests:[...character.interests]},dirty:false}}
export function editCharacter(state,changes){if(!state.character)return state;return createCharacter(state,{...state.character.identity,...changes,name:changes.name||state.character.name})}
export function resolveStudioState(state){if(!state.character)throw new Error('Character Core required before compilation');return {character:clone(state.character),expression:{styleMix:clone(state.styleMix),interests:clone(state.interestState),wardrobe:clone(state.wardrobe)},scene:clone(state.scene||{name:'Unassigned'}),visual:clone(state.visualSettings),provenance:{sources:['working-state'],locks:Object.keys(state.character.locks).filter(k=>state.character.locks[k])}}}
export const MockCompiler=Object.freeze({compile(resolved){const c=resolved.character;return `A photoreal editorial portrait of ${c.name}, a ${c.identity.age}-year-old ${c.identity.occupation} in ${c.identity.location}. ${c.personality.traits.join(', ')} character direction, ${resolved.visual.photography.lens} lens, ${resolved.visual.photography.angle} composition, ${resolved.visual.lighting.behaviour} light.`}});
export function compilePrompt(state,compiler=MockCompiler,options={}){const source=resolveStudioState(state);const prompt={id:`prompt_${Date.now()}`,characterId:state.character.id,createdAt:new Date().toISOString(),compiler:{provider:options.provider||'mock',model:options.model||'studio-baseline',profile:options.profile||'photoreal-director'},sourceState:source,text:compiler.compile(source,options),edited:false};return {...state,compiledPrompts:[prompt,...state.compiledPrompts],dirty:false,lastPrompt:prompt}}
export function createTake(state,variationReason='new-take'){if(!state.character)throw new Error('Character Core required before creating a Take');const take={id:`take_${Date.now()}`,createdAt:new Date().toISOString(),image:null,characterId:state.character.id,characterRevision:state.character.revision,stateSnapshot:clone({...state,takes:[],compiledPrompts:[],lastPrompt:undefined}),compiledPromptId:state.lastPrompt?.id||null,parentTakeId:state.selectedTake||null,variationReason};return {...state,takes:[...state.takes,take],selectedTake:take.id,dirty:false}}
export function promoteTake(state,takeId){if(!state.takes.some(t=>t.id===takeId))return state;return {...state,selectedTake:takeId,dirty:false}}
if(typeof module!=='undefined')module.exports={blankState,STAGE_MODES,stageMode,createCharacter,editCharacter,resolveStudioState,MockCompiler,compilePrompt,createTake,promoteTake};
