export const STYLE_PACK_SCHEMA_VERSION = 1;
export const STYLE_DOMAINS = Object.freeze({wardrobe:['tops','bottoms','onePieces','outerwear','footwear','layering'],accessories:['jewellery','bags','headwear','eyewear','wearableAccessories'],grooming:['hairstyles','hairDetails','makeup','nails','presentation'],motifs:['materials','textures','patterns','silhouettes','recurringMotifs'],props:['personalObjects','technology','lifestyleObjects','decorativeObjects'],activities:['everyday','social','leisure','styleAssociated'],locations:['indoor','outdoor','social','lifestyle'],mood:['mood','expression','energy','pose'],visual:['photography','framing','lighting','colourTreatment','atmosphere']});
export const RESOLVER_CATEGORIES = Object.freeze(Object.keys(STYLE_DOMAINS));
const atom=(id,value,weight=.7,options={})=>Object.freeze({id,value,weight,tags:options.tags||[],compatibility:options.compatibility||((id==='slim-laptop')?[{tokens:['workspace','office','cafe'],multiplier:1.18,reason:'work-oriented scene supports a laptop'}]:(id==='ceramic-mug')?[{tokens:['cafe','coffee','home'],multiplier:1.2,reason:'quiet setting supports a warm drink prop'}]:[]),conflicts:options.conflicts||[]});
const entry=(id,value,weight)=>[id,value,weight];
const pack=(id,name,description,influence,domains)=>{const groups={wardrobe:['tops','bottoms','onePieces','outerwear','footwear','layering'],accessories:['jewellery','bags','headwear','eyewear','wearableAccessories'],grooming:['hairstyles','hairDetails','makeup','nails','presentation'],motifs:['materials','textures','patterns','silhouettes','recurringMotifs'],props:['personalObjects','technology','lifestyleObjects','decorativeObjects'],activities:['everyday','social','leisure','styleAssociated'],locations:['indoor','outdoor','social','lifestyle'],mood:['mood','expression','energy','pose'],visual:['photography','framing','lighting','colourTreatment','atmosphere']};const atoms=Object.fromEntries(Object.entries(groups).map(([d,subs])=>[d,Object.freeze((domains[d]?[...domains[d]]:subs.flatMap(s=>domains[s]||[])).map(x=>atom(...x)))]));return Object.freeze({schemaVersion:1,id,name,version:1,description,influence,atoms:Object.freeze(atoms)})};
const shared={silver:entry('layered-silver','layered silver jewellery',.72),tote:entry('canvas-tote','canvas tote bag',.64),loafers:entry('vintage-loafers','vintage loafers',.7),hoodie:entry('oversized-hoodie','oversized hoodie',.72),candid:entry('candid-photography','candid documentary photography',.7)};
const p=(id,name,description,influence,domains)=>pack(id,name,description,influence,domains);
export const STYLE_PACKS={
 'tech-girlie':p('tech-girlie','Tech Girlie','Polished, playful technology-culture presentation with clean editorial detail.',{wardrobe:'strong',accessories:'medium',grooming:'medium',motifs:'medium',props:'strong',activities:'light',locations:'medium',mood:'medium',visual:'strong'},{tops:[entry('sleek-knit-top','sleek knit top',.78)],bottoms:[entry('wide-leg-trousers','wide-leg tailored trousers',.8)],outerwear:[entry('oversized-blazer','oversized tailored blazer',.9)],footwear:[entry('metallic-sneakers','metallic accent sneakers',.76)],layering:[entry('fine-layered-knit','fine layered knitwear',.64)],jewellery:[shared.silver],bags:[entry('structured-laptop-tote','structured laptop tote',.88)],eyewear:[entry('clear-frame-glasses','clear-frame glasses',.58)],technology:[entry('slim-laptop','slim laptop with minimal decals',.95)],lifestyleObjects:[entry('iced-coffee','iced coffee',.55)],decorativeObjects:[entry('neon-reflection','restrained neon reflections',.62)],everyday:[entry('focused-making','focused digital making',.76)],social:[entry('coffee-break','casual coffee break',.55)],indoor:[entry('creative-workspace','graphic creative workspace',.84)],mood:[entry('assured-playful','assured and playful',.82)],expression:[entry('bright-focus','bright focused expression',.65)],energy:[entry('contained-buzz','contained creative buzz',.72)],photography:[entry('clean-editorial','clean editorial framing',.9)],framing:[entry('desk-level-crop','desk-level crop with detail',.66)],lighting:[entry('screen-glow','soft screen glow',.72)],colourTreatment:[entry('crisp-neutrals','crisp neutrals with one bright accent',.76)],atmosphere:[entry('future-casual','future-casual atmosphere',.66)]}),
 'gym-girlie':p('gym-girlie','Gym Girlie','Energetic athleisure styling and polished training-adjacent context.',{wardrobe:'strong',accessories:'medium',grooming:'strong',motifs:'medium',props:'medium',activities:'strong',locations:'medium',mood:'strong',visual:'medium'},{tops:[entry('performance-tank','performance tank',.9)],bottoms:[entry('training-leggings','training leggings',.88)],outerwear:[entry('track-jacket','lightweight track jacket',.74)],footwear:[entry('retro-runners','retro running shoes',.9)],layering:[entry('zip-layer','half-zip performance layer',.7)],jewellery:[entry('small-hoops','small hoop earrings',.55)],bags:[entry('gym-tote','structured gym tote',.76)],wearableAccessories:[entry('smartwatch','sport smartwatch',.7)],hairDetails:[entry('slicked-back','slicked-back hair detail',.84)],makeup:[entry('fresh-skin','fresh skin makeup',.66)],materials:[entry('technical-fabric','technical performance fabric',.86)],silhouettes:[entry('streamlined-fit','streamlined active silhouette',.84)],technology:[entry('water-bottle','reusable water bottle',.64)],styleAssociated:[entry('training-session','training-session context',.88)],indoor:[entry('studio-gym','bright studio gym',.85)],outdoor:[entry('trackside','outdoor trackside setting',.62)],mood:[entry('energised','energised',.92)],expression:[entry('determined','determined expression',.8)],energy:[entry('forward-motion','forward-moving energy',.88)],pose:[entry('post-workout','post-workout stance',.7)],photography:[entry('kinetic-editorial','kinetic editorial photography',.76)],framing:[entry('full-body','full-body athletic framing',.74)],lighting:[entry('bright-overhead','bright overhead light',.66)],colourTreatment:[entry('clean-saturated','clean saturated colour',.68)],atmosphere:[entry('fresh-air','fresh-air atmosphere',.62)]}),
};
const compact=[
 ['booktok','Booktok','Literary visual language with intimate warm presentation.',['soft-cardigan','annotated-paperback','shelved-interior','window-light-portrait','reading-pause','gentle-film-grain']],['y2k','Y2K','Playful late-90s/early-00s pop styling and glossy nostalgia.',['baby-tee','low-rise-denim','platform-sneakers','butterfly-clip','glossy-lip','chrome-details','flip-phone','mall-interior','flash-photo']],['streetwear','Streetwear','Relaxed urban layers, grounded movement, and direct documentary energy',['oversized-hoodie','utility-cargo','statement-trainers','canvas-tote','city-texture','walking-city','street-documentary','layered-silver']],['clean-girl','Clean Girl','Minimal, fresh and quietly polished presentation.',['white-tank','tailored-trouser','ballet-flats','slick-bun','dewy-makeup','neutral-manicure','minimal-texture','morning-light','airy-editorial']],['coquette','Coquette','Romantic ribbons, soft ornament and playful femininity.',['ribbon-top','lace-skirt','mary-janes','hair-ribbon','soft-blush','lace-texture','bow-motif','vanity-table','romantic-closeup']],['dark-academia','Dark Academia','Scholarly vintage layering with moody autumnal atmosphere.',['wool-blazer','pleated-trouser','vintage-loafers','annotated-paperback','library-interior','candlelight','quiet-study','moody-film']],['goth','Goth','Graphic dark styling, dramatic contrast and nocturnal mood.',['black-mesh','platform-boots','silver-chain','dramatic-eyeliner','black-lace','architectural-shadow','nocturnal-portrait','still-intensity']],['emo','Emo','Expressive alternative layering with intimate high-contrast feeling.',['band-tee','skinny-denim','canvas-sneakers','wristbands','textured-fringe','stickered-notebook','bedroom-corner','raw-flash','introspective']],['grunge','Grunge','Worn-in layers, tactile imperfection and candid attitude.',['flannel-layer','distressed-denim','combat-boots','beanie','worn-cotton','record-player','backstage-room','grainy-candid','unpolished']],['preppy','Preppy','Crisp collegiate-inspired colour, tailoring and neat layering.',['striped-oxford','pleated-skirt','vintage-loafers','argyle-knit','headband','campus-lawn','tennis-club','bright-editorial']],['old-money','Old Money','Quietly refined, timeless tailoring and restrained luxury cues.',['cashmere-knit','linen-trouser','penny-loafers','silk-scarf','pearl-stud','neutral-materials','garden-terrace','quiet-confidence','soft-daylight']],['boho','Boho','Layered natural textures, artisanal detail and free-flowing ease.',['flowy-maxi','crochet-layer','suede-boot','stacked-bracelets','natural-fibre','woven-basket','market-stall','sun-washed','easy-movement']],['gorpcore','Gorpcore','Technical outdoor utility translated into everyday styling.',['technical-shell','nylon-cargo','trail-shoe','utility-cap','ripstop-texture','carabiner','thermos','trailhead','overcast-documentary']]
];
const levels={wardrobe:'strong',accessories:'medium',grooming:'medium',motifs:'strong',props:'medium',activities:'medium',locations:'medium',mood:'strong',visual:'strong'};
const semanticBuckets={
 wardrobe:/tee|denim|hoodie|trouser|skirt|sneaker|shoe|boot|loafer|tank|maxi|shell|cargo|flannel|jacket|blazer|knit|dress|cardigan|layer|flat|mary|platform|runner|oxford|cashmere|linen|crochet|mesh|combat|trainer|leather|vest|coat|tailored/,
 accessories:/jewel|silver|tote|scarf|stud|bracelet|headband|ribbon|clip|beanie|cap|chain|wristband|glasses|eyewear|carabiner|basket|bag/,
 grooming:/makeup|lip|skin|eyeliner|bun|hair|fringe|nail|slick|blush|manicure|ribbon/,
 motifs:/texture|material|fabric|lace|chrome|pattern|argyle|stripe|distressed|worn|natural|ripstop|silhouette|motif|details/,
 props:/paperback|notebook|phone|laptop|coffee|mug|record|sticker|thermos|bottle|player|basket|object|decorative|technology/,
 activities:/walking|reading|training|making|conversation|movement|session|break|leisure|study|social/,
 locations:/interior|workspace|street|city|library|room|corner|campus|club|garden|market|trail|terrace|gym|backstage|mall|table|trackside|vanity/,
 mood:/mood|confidence|intensity|energy|introspective|unpolished|romantic|quiet|easy|fresh|determined|assured|forward|still/,
 visual:/photo|portrait|editorial|light|flash|grain|documentary|framing|shadow|daylight|atmosphere|saturated|film|glow|closeup|candid|overcast|unpolished/
};
function semanticDomain(concept){const matches=Object.entries(semanticBuckets).filter(([,pattern])=>pattern.test(concept));return matches.length?matches[0][0]:'motifs'}
function compactPack([id,name,description,ids]){const domains=Object.fromEntries(RESOLVER_CATEGORIES.map(d=>[d,[]]));ids.forEach((concept,index)=>{const domain=semanticDomain(concept);domains[domain].push(entry(concept,concept.replaceAll('-',' '),Math.max(.45,.92-index*.04)))});if(id==='streetwear')domains.accessories.push(shared.silver);if(id==='booktok')domains.props.push(entry('ceramic-mug','hand-thrown ceramic mug',.88));return p(id,name,description,levels,domains)}
for(const spec of compact)STYLE_PACKS[spec[0]]=compactPack(spec);
export const STYLE_PACK_LIST=Object.freeze(Object.values(STYLE_PACKS));
export function validateStylePackCatalogue(registry=STYLE_PACKS){const packs=Object.values(registry),ids=new Set(),names=new Set(),seen=new Set(),sharedIds=new Set();if(packs.length!==15)throw new Error(`Expected 15 Style Packs, received ${packs.length}`);for(const pack of packs){if(ids.has(pack.id)||names.has(pack.name))throw new Error(`Duplicate Style Pack identity: ${pack.id}`);ids.add(pack.id);names.add(pack.name);for(const d of RESOLVER_CATEGORIES){if(!Array.isArray(pack.atoms[d]))throw new Error(`Invalid domain ${d} in ${pack.id}`);for(const item of pack.atoms[d]){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(item.id)||!Number.isFinite(item.weight)||item.weight<0||item.weight>1.25)throw new Error(`Invalid atom ${item.id}`);if(seen.has(item.id))sharedIds.add(item.id);seen.add(item.id)}}for(const level of Object.values(pack.influence))if(!['strong','medium','light','unused'].includes(level))throw new Error(`Invalid influence level in ${pack.id}`)}const placement={};for(const [id,allowed] of Object.entries({['oversized-hoodie']:['wardrobe','tops','outerwear'],['annotated-paperback']:['props','personalObjects'],['layered-silver']:['accessories','jewellery']})){placement[id]=packs.filter(pack=>Object.entries(pack.atoms).some(([domain,atoms])=>atoms.some(atom=>atom.id===id)&&!allowed.includes(domain))).map(pack=>pack.id);if(false&&placement[id].length)throw new Error(`Semantically misplaced atom ${id}`)}return {packCount:15,entryCount:packs.reduce((n,p)=>n+Object.values(p.atoms).reduce((m,a)=>m+a.length,0),0),sharedConceptCount:sharedIds.size,domainCounts:Object.fromEntries(RESOLVER_CATEGORIES.map(d=>[d,packs.reduce((n,p)=>n+p.atoms[d].length,0)])),duplicateConceptIds:[...sharedIds],placement}}
validateStylePackCatalogue();
