import test from 'node:test';
import assert from 'node:assert/strict';
import {createLibraryRegistry,searchLibrary,validateLibraryRegistry,coverageFor,coverageDiagnostics,relatedHobbiesForInterest,validateCandidates,prepareEnrichmentOperation,LIBRARY_SCHEMA_VERSION} from '../library-data.js';

const scenes=[{id:'cafe',name:'Café',location:'warm indoor coffee shop',activity:'conversation',ambience:'warm'}];
const registry=createLibraryRegistry({scenes,state:{character:{id:'char-1',name:'Rin',identity:{occupation:'Sound designer'}},interestState:{characterInterests:['field recording']}}});

test('library registry is versioned, unique and provenance-safe',()=>{assert.equal(LIBRARY_SCHEMA_VERSION,2);assert.equal(validateLibraryRegistry(registry).categoryCount,12);assert.equal(new Set(registry.map(category=>category.id)).size,12);assert.ok(registry.flatMap(category=>category.families).flatMap(family=>family.entries).every(entry=>['core','user','imported','generated'].includes(entry.source)))});
test('production domains are enriched and Character Core remains separate',()=>{assert.ok(searchLibrary(registry,'Rin').some(category=>category.id==='names'));assert.ok(searchLibrary(registry,'Sound designer').some(category=>category.id==='occupations'));assert.ok(searchLibrary(registry,'Café').some(category=>category.id==='geography'));const interests=registry.find(category=>category.id==='interests'),hobbies=registry.find(category=>category.id==='hobbies');assert.ok(interests.entryCount>=150);assert.ok(hobbies.entryCount>=150);assert.ok(interests.families.every(family=>family.fixture===false));assert.ok(hobbies.families.every(family=>family.domain==='hobby'));assert.equal(interests.families.find(family=>family.id==='gaming').entries.length,16)});
test('search spans categories, families, subcategories and entries with category filtering',()=>{assert.ok(searchLibrary(registry,'Game development').some(category=>category.id==='interests'));assert.ok(searchLibrary(registry,'field recording').some(category=>category.id==='interests'));assert.deepEqual(searchLibrary(registry,'editorial','style-aesthetics').map(category=>category.id),['style-aesthetics']);assert.equal(searchLibrary(registry,'no-such-content').length,0)});
test('coverage has stable thin-to-healthy thresholds',()=>{assert.deepEqual([coverageFor(0),coverageFor(2),coverageFor(8),coverageFor(20)],['poor','low','good','healthy'])});
test('coverage, relationships and enrichment operations are structured',()=>{const report=coverageDiagnostics(registry,'hobbies');assert.equal(report.category,'healthy');assert.equal(report.thinFamilies.length,0);assert.ok(relatedHobbiesForInterest('Photography').some(link=>link.hobbyId==='street-photography'));const prepared=prepareEnrichmentOperation('Fill Gaps','hobbies','outdoors',registry);assert.equal(prepared.mutatesCore,false);assert.equal(prepared.reviewStatus,'pending')});
test('candidate validation rejects duplicates and invalid metadata while preserving provenance',()=>{const result=validateCandidates([{id:'new-1',label:'Trail cartography',family:'outdoors',source:'generated'},{id:'new-1',label:'Other',family:'outdoors',source:'generated'},{id:'new-2',label:'New thing',family:'outdoors',source:'generated',metadata:{activityLevel:'extreme'}},{id:'new-3',label:'Fresh idea',family:'outdoors',source:'core'}],registry);assert.equal(result.valid.length,2);assert.equal(result.valid[0].reviewStatus,'pending');assert.equal(result.errors.length,2)});
