import test from 'node:test';
import assert from 'node:assert/strict';
import {blankState,createCharacter,createTake,restoreState,serializeState} from '../studio-core.js';
import {commitCharacter,deleteCharacter} from '../character-library.js';
import {createProject,updateProject,archiveProject,deleteProject,attachCharacter,detachCharacter,attachTake,openProjectCharacter,openProjectTake,migrateProjectState} from '../project-library.js';
import {createCloudStore} from '../cloud-store.js';

function fixture(){let state=createCharacter(blankState(),{id:'char-a',name:'A'});const first=state.character;state=createCharacter({...state,character:null,activeCharacterId:null},{id:'char-b',name:'B'});const second=state.character;state=commitCharacter(state,first);state=createTake(state,'first');state=commitCharacter(state,second);state=createTake(state,'second');return state;}

test('legacy state migrates with empty Project defaults',()=>{const restored=restoreState(JSON.stringify({character:null,characters:[],takes:[]}));assert.deepEqual(restored.projects,[]);assert.equal(restored.activeProjectId,null)});
test('multiple Projects retain stable IDs and timestamps',()=>{let state=fixture();state=createProject(state,{name:'One'},{id:'project-one',now:'2026-01-01T00:00:00.000Z'});state=createProject(state,{name:'Two'},{id:'project-two',now:'2026-01-02T00:00:00.000Z'});state=updateProject(state,'project-one',{brief:'Updated'},{now:'2026-01-03T00:00:00.000Z'});assert.deepEqual(state.projects.map(project=>project.id),['project-one','project-two']);assert.equal(state.projects[0].createdAt,'2026-01-01T00:00:00.000Z');assert.equal(state.projects[0].updatedAt,'2026-01-03T00:00:00.000Z')});
test('Characters and Takes may be referenced by multiple Projects without ownership changes',()=>{let state=fixture(),take=state.takes[0],character=state.characters[0];state=createProject(state,{name:'One'},{id:'one'});state=createProject(state,{name:'Two'},{id:'two'});for(const id of ['one','two']){state=attachCharacter(state,id,character.id);state=attachTake(state,id,take.id)}assert.ok(state.projects.every(project=>project.characterIds.includes(character.id)&&project.takeIds.includes(take.id)));assert.equal(state.takes[0].characterId,take.characterId)});
test('attaching or normalizing a Take includes its owning Character',()=>{let state=fixture(),take=state.takes.find(item=>item.characterId==='char-b');state=createProject(state,{name:'One'},{id:'one'});state=attachTake(state,'one',take.id);assert.deepEqual(state.projects[0].characterIds,['char-b']);assert.deepEqual(state.projects[0].takeIds,[take.id]);state=createProject(state,{name:'Two',takeIds:[take.id]},{id:'two'});assert.deepEqual(state.projects[1].characterIds,['char-b'])});
test('detaching a Character also detaches its owned Takes',()=>{let state=fixture(),take=state.takes.find(item=>item.characterId==='char-a');state=createProject(state,{name:'One',takeIds:[take.id]},{id:'one'});state=detachCharacter(state,'one','char-a');assert.deepEqual(state.projects[0].characterIds,[]);assert.deepEqual(state.projects[0].takeIds,[])});
test('opening Project references uses Character ownership and blocks invalid cross-character Takes',()=>{let state=fixture(),take=state.takes.find(item=>item.characterId==='char-a');state=createProject(state,{name:'One',characterIds:['char-a'],takeIds:[take.id]},{id:'one'});state=openProjectCharacter(state,'one','char-a');assert.equal(state.activeCharacterId,'char-a');state=openProjectTake({...state,selectedTake:null},'one',take.id);assert.equal(state.activeCharacterId,'char-a');assert.equal(state.selectedTake,take.id);const invalid={...take,id:'bad-take',characterId:'missing'};const unchanged=openProjectTake({...state,takes:[...state.takes,invalid],projects:[{...state.projects[0],takeIds:[...state.projects[0].takeIds,invalid.id]}],selectedTake:null},'one',invalid.id);assert.equal(unchanged.selectedTake,null);assert.equal(openProjectTake({...state,selectedTake:null},'one',state.takes.find(item=>item.characterId==='char-b').id).selectedTake,null)});
test('Project archive restore and deletion never mutate Characters or Takes',()=>{let state=fixture();state=createProject(state,{name:'One'},{id:'one'});const characters=structuredClone(state.characters),takes=structuredClone(state.takes);state=archiveProject(state,'one',true);assert.equal(state.projects[0].status,'archived');state=archiveProject(state,'one',false);assert.equal(state.projects[0].status,'active');state=deleteProject(state,'one');assert.deepEqual(state.characters,characters);assert.deepEqual(state.takes,takes)});
test('Character deletion removes stale Project Character and Take references',()=>{let state=fixture(),owned=state.takes.filter(take=>take.characterId==='char-a').map(take=>take.id);state=createProject(state,{name:'One',characterIds:['char-a','char-b'],takeIds:state.takes.map(take=>take.id)},{id:'one'});state=deleteCharacter(state,'char-a',{force:true});assert.deepEqual(state.projects[0].characterIds,['char-b']);assert.ok(owned.every(id=>!state.projects[0].takeIds.includes(id)))});
test('Project state survives save reload and local/cloud adapters',async()=>{let state=fixture();state=createProject(state,{name:'One',characterIds:['char-a'],takeIds:[state.takes[0].id]},{id:'one'});const restored=restoreState(serializeState(state));assert.deepEqual(restored.projects,state.projects);const data=new Map(),local=createCloudStore({local:{getItem:key=>data.get(key)||null,setItem:(key,value)=>data.set(key,value)}});await local.saveCharacter(state,'local');assert.deepEqual(JSON.parse(data.get('promptforge-studio-v2')).projects,state.projects);let payload;const cloud=createCloudStore({client:{from:()=>({upsert:async value=>{payload=value;return {error:null}}})}});await cloud.saveCharacter(state,'cloud');assert.deepEqual(payload.state.projects,state.projects)});
test('migration removes stale Character and Take references safely',()=>{const migrated=migrateProjectState({...fixture(),projects:[{id:'one',name:'One',characterIds:['char-a','missing'],takeIds:['missing']}],activeProjectId:'one'});assert.deepEqual(migrated.projects[0].characterIds,['char-a']);assert.deepEqual(migrated.projects[0].takeIds,[])});
