import test from 'node:test';
import assert from 'node:assert/strict';
import {blankState,createCharacter,createTake,restoreState} from '../studio-core.js';
import {TAKE_SEMANTIC_SCHEMA_VERSION,projectTakeSemantics,findTakesBySemantic,scoreTakeSemanticMatch,takeSemanticsToConcepts} from '../take-semantics.js';

function representative(){return {styleMix:{influences:[{packId:'tech-girlie',weight:70},{packId:'gym-girlie',weight:30}]},scene:{id:'tokyo-night',name:'Tokyo at night',location:'Tokyo',activity:'Candid street walk',ambience:'night',mood:'Restless'},wardrobe:{items:['Oversized charcoal hoodie'],slots:{accessory:'Silver headphones',shoes:'Vintage loafers'}},visualSettings:{photography:{shotType:'Candid',lens:'35mm',angle:'Eye level'},lighting:{behaviour:'Neon',colourTreatment:'Warm'},expression:{expression:'Quiet intensity'}}};}

test('projects Take semantics from actual structured snapshot paths',()=>{const semantic=projectTakeSemantics(representative());assert.equal(semantic.schemaVersion,TAKE_SEMANTIC_SCHEMA_VERSION);assert.deepEqual(semantic.style.map(item=>[item.id,item.weight]),[['tech-girlie',70],['gym-girlie',30]]);assert.ok(semantic.setting.some(item=>item.id==='tokyo-at-night'&&item.sceneId==='tokyo-night'));assert.ok(semantic.setting.some(item=>item.id==='tokyo'));assert.deepEqual(semantic.activity.map(item=>item.id),['candid-street-walk']);assert.ok(semantic.wardrobe.some(item=>item.id==='silver-headphones'&&item.slot==='accessory'));assert.deepEqual(semantic.camera.map(item=>item.id),['candid','35mm','eye-level']);assert.deepEqual(semantic.lighting.map(item=>item.id),['neon','warm']);assert.deepEqual(semantic.mood.map(item=>item.id),['quiet-intensity','restless']);assert.equal(new Set(semantic.tags).size,semantic.tags.length);});
test('missing structured domains remain empty and tags are deterministic',()=>{const first=projectTakeSemantics({scene:{id:'x',name:'Same',location:'Same'}}),second=projectTakeSemantics({scene:{id:'x',name:'Same',location:'Same'}});assert.deepEqual(first,second);assert.deepEqual(first.activity,[]);assert.deepEqual(first.wardrobe,[]);assert.deepEqual(first.camera,[]);assert.deepEqual(first.lighting,[]);assert.deepEqual(first.mood,[]);assert.deepEqual(first.tags,['same']);});
test('new Takes receive semantics without changing their immutable snapshot',()=>{let state=createCharacter(blankState(),{id:'char-a',name:'A'});state={...state,...representative()};state=createTake(state,'test');const take=state.takes[0];assert.equal(take.semantic.schemaVersion,1);assert.equal(take.stateSnapshot.scene.name,'Tokyo at night');state.scene.name='Changed';assert.equal(take.stateSnapshot.scene.name,'Tokyo at night');});
test('restore backfills old Takes idempotently without changing Take envelope fields',()=>{const old={id:'take-old',characterId:'char-a',characterRevision:7,compiledPromptId:'prompt-a',parentTakeId:'take-parent',stateSnapshot:representative()};const saved={...blankState(),character:{id:'char-a',revision:7},characters:[{id:'char-a',revision:7}],activeCharacterId:'char-a',takes:[old]};const once=restoreState(JSON.stringify(saved)),twice=restoreState(JSON.stringify(once));assert.equal(once.takes[0].id,old.id);assert.equal(once.takes[0].characterId,old.characterId);assert.equal(once.takes[0].characterRevision,old.characterRevision);assert.equal(once.takes[0].parentTakeId,old.parentTakeId);assert.deepEqual(once.takes[0].stateSnapshot,old.stateSnapshot);assert.deepEqual(twice.takes,once.takes);});
test('semantic querying and Inspiration concepts use normalized structured values',()=>{const take={id:'one',stateSnapshot:representative()},other={id:'two',stateSnapshot:{}};assert.deepEqual(findTakesBySemantic([take,other],{camera:['35mm'],setting:['tokyo']}),[take]);assert.deepEqual(scoreTakeSemanticMatch(take,{camera:['35mm','85mm']}),{matched:1,requested:2,score:.5});assert.ok(takeSemanticsToConcepts(take).some(concept=>concept.domain==='style'&&concept.id==='tech-girlie'));});
